# Generated by Django 3.2.6 on 2021-08-22 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('legs', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('color', models.CharField(max_length=200)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.family')),
            ],
        ),
    ]
